version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - data:/data
    depends_on:
      - redis
      - db
    restart: always
  redis:
    image: redis:7
    restart: always
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bim
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
volumes:
  data:
  db_data:
